# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_video_yolo = QtWidgets.QLabel(self.centralwidget)
        self.label_video_yolo.setGeometry(QtCore.QRect(1, 1, 201, 141))
        self.label_video_yolo.setObjectName("label_video_yolo")
        self.label_pic = QtWidgets.QLabel(self.centralwidget)
        self.label_pic.setGeometry(QtCore.QRect(0, 180, 201, 151))
        self.label_pic.setObjectName("label_pic")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(330, 280, 161, 71))
        self.pushButton_start.setObjectName("pushButton_start")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(270, 10, 171, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_label_recycle = QtWidgets.QLabel(self.widget)
        self.text_label_recycle.setObjectName("text_label_recycle")
        self.verticalLayout.addWidget(self.text_label_recycle)
        self.text_label_other = QtWidgets.QLabel(self.widget)
        self.text_label_other.setObjectName("text_label_other")
        self.verticalLayout.addWidget(self.text_label_other)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(440, 10, 171, 131))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_label_harmful = QtWidgets.QLabel(self.widget1)
        self.text_label_harmful.setObjectName("text_label_harmful")
        self.verticalLayout_2.addWidget(self.text_label_harmful)
        self.text_label_other_kitchen = QtWidgets.QLabel(self.widget1)
        self.text_label_other_kitchen.setObjectName("text_label_other_kitchen")
        self.verticalLayout_2.addWidget(self.text_label_other_kitchen)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_video_yolo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">TextLabel</span></p><p><br/></p></body></html>"))
        self.label_pic.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">TextLabel</span></p><p><br/></p></body></html>"))
        self.pushButton_start.setText(_translate("MainWindow", "START"))
        self.text_label_recycle.setText(_translate("MainWindow", "TextLabel"))
        self.text_label_other.setText(_translate("MainWindow", "TextLabel"))
        self.text_label_harmful.setText(_translate("MainWindow", "TextLabel"))
        self.text_label_other_kitchen.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
